### PR TITLE
Mehmet a

### PR DESCRIPTION
**Pull request by Mehmet-Afacan**
This branch from MehmetA

### CODE REVIEW

**Comment by Mehmet-Afacan** [comment]
It is gonna be OK

**Review by ALIYILD — COMMENTED** [review]
come on abi , it is gonna be wild.......

**Comment by ALIYILD** [comment]
:-)

**Comment by Mehmet-Afacan** [comment]
Can anyone else also join this conversation or it is just between us

**Comment by ALIYILD** [comment]
all of the fired by the boss abi:-) Only two of you AWAKE one of you others is KALDIRIMLAR ;)(NFK)

**Comment by Mehmet-Afacan** [comment]
THE BOSS.... By the way , long live Ali abi :))

**Pull request merged**
